onlineRetailer:
  salesTaxRate: 0.20
  deliveryCharge:
    normal: 2.50
    threshold: 3000
---
spring:
  profiles: development
resources:
  db: H2
  logs: C:\temp\logs\
  secure: false
---
spring:
  profiles: production
resources:
  db: Oracle
  logs: //PROD_SERVER/logs/
  secure: true
---